# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialWidgetsDemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=32)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='')),
                ('file_path_field', models.FilePathField()),
                ('float_field', models.FloatField()),
                ('integer_field', models.IntegerField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('null_boolean_field', models.NullBooleanField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialWidgetsForeignKeyDemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialWidgetsManyToManyDemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='materialwidgetsdemomodel',
            name='foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.MaterialWidgetsForeignKeyDemoModel'),
        ),
        migrations.AddField(
            model_name='materialwidgetsdemomodel',
            name='many_to_many_field',
            field=models.ManyToManyField(to='demo.MaterialWidgetsManyToManyDemoModel'),
        ),
    ]
