# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='big_integer_field',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='char_field',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='date_time_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='decimal_field',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='email_field',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='file_field',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='file_path_field',
            field=models.FilePathField(blank=True, path='/demo/images'),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='float_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.MaterialWidgetsForeignKeyDemoModel'),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='integer_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='many_to_many_field',
            field=models.ManyToManyField(blank=True, to='demo.MaterialWidgetsManyToManyDemoModel'),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='positive_integer_field',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='positive_small_integer_field',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='slug_field',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='small_integer_field',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialwidgetsdemomodel',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
    ]
