# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialWidgetsForeignKeyTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialWidgetsManyToManyTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialWidgetsTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField(blank=True, null=True)),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(blank=True, max_length=32, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_field', models.FileField(blank=True, upload_to='')),
                ('file_path_field', models.FilePathField(blank=True, path='/demo/images')),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('generic_ip_address_field', models.GenericIPAddressField(blank=True, null=True)),
                ('null_boolean_field', models.NullBooleanField()),
                ('positive_integer_field', models.PositiveIntegerField(blank=True, null=True)),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug_field', models.SlugField(blank=True, null=True)),
                ('small_integer_field', models.SmallIntegerField(blank=True, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('url_field', models.URLField(blank=True, null=True)),
                ('foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material_widgets_tests.MaterialWidgetsForeignKeyTestModel')),
                ('many_to_many_field', models.ManyToManyField(blank=True, to='material_widgets_tests.MaterialWidgetsManyToManyTestModel')),
            ],
        ),
    ]
